# Site settings
title: words for humans about computers
# header-img: img/home-bg.png
header-img: img/rocks.jpg
email: donnamcla@gmail.com
copyright_name: Donna Hogan
author: Donna Hogan
description: > # this means to ignore newlines until "baseurl:"
  In which I occasionally chronicle my path from scientist to software developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: donna_ddmh
github_username:  ddhogan
learn_profile: ddhogan
email_username: donnamcla@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed, jemoji]
